### ISSUE TITLE
What's the best way to write unit tests for Web API controllers that use Saule?

### ISSUE THREAD

**Issue by bxh** [joukevandermaas/saule#107]
I'm working on a backend Web API for an Ember app to consume. I'm wondering what the best way is to test my API endpoints before I hand them over to my front end teammates. Thanks!

**Comment by joukevandermaas** [comment]
We have some tests in Saule's [test suite](https://github.com/joukevandermaas/saule/blob/master/Tests/Integration/JsonApiMediaTypeFormatterTests.cs) that fire a request at the server and check the response. Maybe those can be of help to you?

If you don't care so much about the exact JSON that's returned, you can just unit test your controller as you always would, and check the resulting object rather than JSON response.

**Comment by bxh** [comment]
Thanks for the feedback. I'm hoping to unit test (in .NET) my controller methods *and* validate the output JSON format. Is that possible?

**Comment by joukevandermaas** [comment]
@bxh It depends on what you call a unit test. The tests I linked should work for you, but they're not typically referred to as 'unit test', since they call into the API from the outside, seeing only what your Ember app would see. If that's what you want, then that's what I recommend.

**Comment by joukevandermaas** [comment]
I'm closing this issue. Feel free to re-open if your question was not answered.
