### ISSUE TITLE
Make Saule easier to work with legacy code

### ISSUE THREAD

**Issue by bxh** [joukevandermaas/saule#108]
I'm working on a web app as part of a large legacy platform in healthcare tech industry. To minimize code changes, I would need to:

1. Use `JsonApiMediaTypeFormatter` while keeping `JsonMediaTypeFormatter` and `XmlMediaTypeFormatter`.

2. Scope `PreprocessingDelegatingHandler` at route level.

Unfortunately, neither of which can be done in a neat way due to the [way](https://github.com/joukevandermaas/saule/blob/master/Saule/Http/HttpConfigExtensions.cs) that Saule is configured. So I'm wondering if you guys are willing to make configuration more flexible.

Concretely, I would remove [line 35](https://github.com/joukevandermaas/saule/blob/master/Saule/Http/HttpConfigExtensions.cs#L35) and expose `PreprocessingDelegatingHandler` as `public`.

What do you think? Or were there any concerns that made you deliberately not do so?

**Comment by joukevandermaas** [comment]
This is in #101. I just published a new pre-release where `PreprocessingDelegatingHandler` is public and `ConfigureJsonApi` has an overload to preserve other formatters.

The reason I made it internal first is because that's my default; I like keeping things private unless there's a good reason not to (like now).

**Comment by bxh** [comment]
Awesome.
