### ISSUE TITLE
Null associations should be serialized to null resource identifier objects

### ISSUE THREAD

**Issue by goo32** [joukevandermaas/saule#125]
From the spec....

> Resource Linkage
> 
> Resource linkage in a compound document allows a client to link together all of the included resource objects without having to GET any URLs via links.
> 
> Resource linkage MUST be represented as one of the following:
> 
> null for empty to-one relationships.
> an empty array ([]) for empty to-many relationships.
> a single resource identifier object for non-empty to-one relationships.
> an array of resource identifier objects for non-empty to-many relationships.

That is....

For empty to-one relationships:

```
"relationships": {
    "author": {
      "links": {
        "self": "http://example.com/articles/1/relationships/author",
        "related": "http://example.com/articles/1/author"
      },
      "data": null
    }
  }
```
And for empty to-many relationships:
```
"relationships": {
    "comments": {
      "links": {
        "self": "http://example.com/articles/1/relationships/comments",
        "related": "http://example.com/articles/1/comments"
      },
      "data": []
    }
  }
```

**Comment by goo32** [comment]
I'll attempt a fix for this.

**Comment by joukevandermaas** [comment]
As far as I can remember, Saule serializes a [related resource link](http://jsonapi.org/format/#document-resource-object-related-resource-links) instead of an included object when the value of a relationship property is `null`.

I think this is in compliance with the spec, and it was added as a convenient way of dynamically deciding whether to side-load resources. I think any PR should keep the current behavior, and add a way to customize it. That way, we don't break existing applications when they update.

**Comment by goo32** [comment]
A way to customize it is definitely needed because the current behavior requires relationship endpoints that return null relationships to keep ember data happy. #126 should address this. Thank you!
