### ISSUE TITLE
Unit test support

### ISSUE THREAD

**Issue by corfor** [joukevandermaas/saule#17]
I would like an easier way to unit test my ApiResource classes, specifically, to verify how they are serializing in regards to related resources.

It would be helpful if ResourceSerializer were made public for this purpose. Then I can write unit tests that are similar to the unit tests found in ResourceSerializerTests.

**Comment by joukevandermaas** [comment]
I want the bulk of the implementation to live in an internal class, because I want to be free to e.g. add dependencies or refactor. However, I do see the value in being able to serialize things outside of web api. 

Maybe we can add a new class that calls into the serializer internally, that can be used for this purpose. I guess it would supply things like the `PaginationContext` somehow, without exposing them to the outside world. Would that serve your needs?

**Comment by corfor** [comment]
Sure. That would work.

**Comment by joukevandermaas** [comment]
:+1: I'll see if I can get something working for you this week.
