### ISSUE TITLE
Project future

### ISSUE THREAD

**Issue by zygimantas** [joukevandermaas/saule#45]
Dear Jouke, excuse me for contacting by raising an issue, but your contact are well kept secret :)

Your project looks very solid! Are there any potential issues which are not logged in "Issues" section? Do you recommend it to start using it in production in next 6 months? Do you know anyone who is also using your library/are you using it in production yourself? Have you tried to use it with dnxcore?

Thank you in advance! If you wish, you can contact me directly: zygimantas berziunas com

**Comment by joukevandermaas** [comment]
There are potential issues of course, but none that I am currently aware of. I am using Saule in one app, and may use it in another soon. Neither of them are currently production-ready, but that is certainly a goal. As far as I know, @corfor is also using Saule in an app.

My goal is to have Saule be production-ready and while it's a relatively young project, I think it's the most complete Json API (1.0) library for C# currently.

As for .Net core, I have not tried it yet. I know some changes will need to be made to be ASP.NET 5 compatible, since we currently rely on action filters. I will likely look into this soon, now that the RC version has been released.

I hope this answers your questions, and thanks for considering Saule.

**Comment by corfor** [comment]
Yes, we are using it in an e-commerce site. I chose it over JsonApi.NET
because it has better separation of concerns by not forcing you to return a
data type inherited from a framework base class; Saule accomplishes its
response modeling via method attributes.

Jouke has been very responsive and quick to support our use cases. I feel
confident using and recommending this JsonAPI  framework.
