### ISSUE TITLE
ASP.NET 5 (vNext) support

### ISSUE THREAD

**Issue by bluemmc** [joukevandermaas/saule#57]
I am using RC1 of ASP.NET 5 (vNext) and would like to use it with saule.

P.S. Saule is cool ! :-)

**Comment by joukevandermaas** [comment]
I would love to support this, but I haven't used ASP.Net 5 personally and I'm not sure what's involved to get it working. From what I understand, action filters (which Saule uses) are a thing of the past, to be replaced by pipeline hooks. In addition, the reflection APIs have changed between .Net 4.5 and Core.

We'll probably end up having to create and maintain a separate Nuget package for this, since those changes are not backwards compatible. It would be nice to have some sort of shared core, but some internals work will have to be done for this. I'll have to spike this sometime in the future, hopefully soon.

**Comment by bluemmc** [comment]
You can install and try the RC1 which is available at "https://get.asp.net/". Big big changes in framework and tooling (for the better) but not necessarily so much for Saule. Filters can be used still along "middleware" for pipeline hooks. System.web dependencies must be changes.

**Comment by robladbrook** [comment]
@joukevandermaas I have created a basic proof of concept spike that might offer some ideas / inspiration: https://github.com/robladbrook/saule-aspnet5

I'll get it production ready (for my needs) until you're in a position to do something properly :)

**Comment by joukevandermaas** [comment]
@robladbrook Awesome work! It looks like my suspicions were more or less correct; we'll have to use a different way to pass properties around since the pipeline has changed and the reflection APIs no longer work the same way.

It looks like most of the code can actually be shared between .Net 4.5 and core though, which is good news. It should be possible to abstract over these things, rather than to use them directly. I'm planning to do some refactoring of Saule internals anyway (specifically the serialization and pagination process, to support #78 and #59), so I'll keep this in mind.

Thanks a lot for doing this!

**Comment by joukevandermaas** [comment]
I'm going to close this issue for now. I don't have any plans to port Saule to .Net Core in the near future, but I'm open to contributions from others.

**Comment by bluemmc** [comment]
It is unfortunate, as it seems .NET core is going to be THE future preferred platform for .NET development as evident from the current momentum. Libraries and tools that do not support .NET core will be left in the dust.

**Comment by joukevandermaas** [comment]
@bluemmc I don't use it, and I don't have enough time to invest in learning the platform and adapting Saule to it. I'd love for others to contribute Core support, and I'll gladly merge PRs towards this goal.
