### ISSUE TITLE
Support for Serializing types with an Id property starting with an underscore ("_id")

### ISSUE THREAD

**Issue by markwalsh-liverpool** [joukevandermaas/saule#80]
I'm trying to serialize the following example type which contains an ID property into a ApiResource:

```csharp
        public class UnderscoreIdPerson
        {
            public string _id { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
            public int? Age { get; set; }
            public int NumberOfLegs { get; set; }
            public Company Job { get; set; }
            public IEnumerable<Person> Friends { get; set; }
        }

        public class UnderscorePersonResource : ApiResource
        {
            public UnderscorePersonResource()
            {
                Attribute(nameof(Person.FirstName));
                Attribute(nameof(Person.LastName));
                Attribute(nameof(Person.Age));

                WithId("_id");
            }
        }
```

This will fail because of the SplitAndLower method in the StringExtensions class treating the underscore as a seperator when executing VerifyPropertyName in the ApiResource class.

Rationale: When using MongoDb, the default name for an Id property is "_id" therefore every single domain object i.e. UnderscoreIdPerson has this underscore Id property by default.  Here is a test to prove it's not possible at the moment:

```csharp
        [Fact(DisplayName = "Uses specified property if it exists for underscore Ids")]
        public void UsesSpecifiedPropertyUnderscoreId()
        {
            var underscorePerson = new UnderscoreIdPerson();

            var target = new ResourceSerializer(underscorePerson, new UnderscorePersonResource(),
                GetUri(id: "abc"), DefaultPathBuilder, null);

            var result = target.Serialize();
            _output.WriteLine(result.ToString());

            var id = result["data"].Value<string>("id");

            Assert.Equal(DefaultObject.Identifier, id);
        }
```

*NB: I inherited a codebase.  I wouldn't ever use "_id" for an ID name, ever.  It's pretty common for people using Mongo not to stipulate their own primary key field so this is probably pertinent to others not just my use case*

**Comment by joukevandermaas** [comment]
I understand why this is a problem for you. Can you point me to the database library/framework you use to map from C# objects to Mongo documents? Maybe there is a way to change the name of the property without also changing how it is stored?

I really like the feature of Saule that seamlessly converts between camel case (convention in the javascript world), dasherized or kebab case (convention in urls and recommended in the JSON API spec) and pascal case (convention in C#). Since JSON API is supposed to be both client and server language agnostic, I suspect it will eventually be used by languages that use snake casing as a convention.

That said, the spec clearly forbids names to *begin* with an underscore, so I'm not against changing the `SplitAndLower` method to ignore those. I'll gladly accept a PR with those changes.

As an aside, I think the way you wrote this issue is great. You clearly say what you expect, show that it doesn't work and where the problem is, and provide the reason for your request. Thanks!

**Comment by markwalsh-liverpool** [comment]
Thanks very much for the compliment on my issue! I thought I'd make up for saying something incorrect about the JSON API spec previously :smile: 

Sure, the [MongoDriver](https://www.nuget.org/packages/MongoDB.Driver) is responsible for that .  I am unsure as the driver recently was upgraded from 1.x to 2 and A LOT changed within that codebase, I believe you can still actually change this as per the answer stipulated [here](http://stackoverflow.com/a/6069830) and also blogged about [here](http://codingcanvas.com/using-mongodb-_id-field-with-c-pocos/), so I don't think this is an issue (yet), this would just mean anyone intending to convert a Resource into a ApiResource would have to have their Id field named correctly in their POCO i.e. "Id" not "_id".  I am going to see whether it is actually possible to rename the "_id" property on the aforementioned UnderscoreIdPerson class (and have it still serialize correctly into Mongo) and get back to you.  This at the moment is definitely just a Mongo implementation specific problem.

**Comment by markwalsh-liverpool** [comment]
I've renamed my "_id" property to "Id" and all is good.  I don't think this needs to be implemented until there is a need for it.

**Comment by joukevandermaas** [comment]
Good to hear! :+1:
